PRAGMA foreign_keys = ON;
CREATE TABLE IF NOT EXISTS users(
    username VARCHAR(20) NOT NULL,
    fullname VARCHAR(40) NOT NULL,
	email VARCHAR(40) NOT NULL,
	filename VARCHAR(64) NOT NULL,
	password VARCHAR(256) NOT NULL,
	created DATETIME DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(username)
);

CREATE TABLE IF NOT EXISTS posts(
	postid INTEGER PRIMARY KEY AUTOINCREMENT,
	filename VARCHAR(64) NOT NULL,
	owner VARCHAR(64) REFERENCES users(username) ON DELETE CASCADE,
	created DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS following(
	username1 VARCHAR(20) REFERENCES users(username) ON DELETE CASCADE,
	username2 VARCHAR(20) REFERENCES users(username) ON DELETE CASCADE,
	created DATETIME DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY(username1, username2)
);

CREATE TABLE IF NOT EXISTS comments(
	commentid INTEGER PRIMARY KEY,
	owner VARCHAR(20) REFERENCES users(username) ON DELETE CASCADE,
	postid INTEGER REFERENCES posts(postid) ON DELETE CASCADE,
	text VARCHAR(1024),
	created DATETIME DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS likes(
	likeid INTEGER PRIMARY KEY,
	owner VARCHAR(20) REFERENCES users(username) ON DELETE CASCADE,
	postid INTEGER REFERENCES posts(postid) ON DELETE CASCADE,
	created DATETIME DEFAULT CURRENT_TIMESTAMP
);
